# TP4
## SVM for MNIST digit number recognition

In [1]:
import numpy as np
from sklearn import decomposition
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV

In [2]:
train_data=np.genfromtxt("dataset/mnist_train.csv",delimiter=",",dtype=np.uint8)
test_data=np.genfromtxt("dataset/mnist_train.csv",delimiter=",",dtype=np.uint8)
print(train_data.shape)
print(test_data.shape)

(60001, 785)
(60001, 785)


In [3]:
# ignore the header
x_train=train_data[1:,1:]
y_train=train_data[1:,0]
x_test=test_data[1:,1:]
y_test=test_data[1:,0]

In [4]:
print("{}/{}".format(x_train.shape,y_train.shape))
print("{}/{}".format(x_test.shape,y_test.shape))

(60000, 784)/(60000,)
(60000, 784)/(60000,)


In [5]:
pca=decomposition.PCA(n_components=100)
x_train=pca.fit_transform(x_train)
x_test=pca.fit_transform(x_test)
print(x_train.shape)
print(x_test.shape)

(60000, 100)
(60000, 100)


In [6]:
scaler = StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)
print(x_train.shape)
print(x_test.shape)

(60000, 100)
(60000, 100)


In [ ]:
parameters = {'kernel':('linear', 'poly', 'rbf', 'sigmoid'), 'C':[1, 5, 10],'gamma':["auto","scale"]}
clf = GridSearchCV(SVC(), parameters)
clf.fit(x_train,y_train)

In [ ]:
# best param C=10, rbf, auto

In [7]:
best_svc=SVC(kernel="rbf",C=10,gamma="auto")
best_svc.fit(x_train,y_train)

SVC(C=10, gamma='auto')

In [8]:
y_pred=best_svc.predict(x_test)

In [9]:
# evaluation
accuracy=accuracy_score(y_test,y_pred)
conf=confusion_matrix(y_test,y_pred)
print("accuracy score: {}".format(accuracy))
print("confusion matrix: {}".format(conf))

accuracy score: 0.9983833333333333
confusion matrix: [[5920    0    0    0    1    1    0    0    1    0]
 [   0 6737    3    0    0    0    0    2    0    0]
 [   0    0 5946    3    1    1    1    3    1    2]
 [   0    0    4 6114    0    6    0    2    4    1]
 [   0    0    1    0 5837    0    0    2    0    2]
 [   0    0    0    4    1 5411    1    0    4    0]
 [   0    0    0    0    1    2 5915    0    0    0]
 [   0    1    3    0    3    1    0 6254    2    1]
 [   0    0    0    4    1    1    0    1 5844    0]
 [   2    0    1    2    4    1    0   11    3 5925]]
