In [ ]:
import numpy as np

#initialize the data
NumberOfIteration = 0
NumberOfState = 4
Rs = [0,0,1,10]
gama = 0.9
x = 0.25
y = 0.25

Ta0 = [[0,0,0,0],
     [0,1-x,0,x],
     [1-y,0,0,y],
     [1,0,0,0]]
Ta1 = [[0,1,0,0],
     [0,0,0,0],
     [0,0,0,0],
     [0,0,0,0]]
Ta2 = [[0,0,1,0],
     [0,0,0,0],
     [0,0,0,0],
     [0,0,0,0]]

Value = np.array([0., 0., 1., 10.])
Previous_Value = np.array([0., 0., 0., 0.])
Action = [0 for col in range(NumberOfState)]
print(Value)

[ 0.  0.  1. 10.]


In [ ]:

flag_stop = False

while(not flag_stop):
  NumberOfIteration = NumberOfIteration + 1

  Vs_Ta0 = np.dot(Ta0, Value)
  Vs_Ta1 = np.dot(Ta1, Value)
  Vs_Ta2 = np.dot(Ta2, Value)

  #find the highest action
  for i in range(NumberOfState):
    Previous_Value[i] = Value[i]
    Value[i] = Rs[i] + gama*max(Vs_Ta0[i],Vs_Ta1[i],Vs_Ta2[i])

  for i in range(NumberOfState):
    if (max(Vs_Ta0[i],Vs_Ta1[i],Vs_Ta2[i]) == Vs_Ta0[i])&(i != 0):
      Action[i] = 0
    elif max(Vs_Ta0[i],Vs_Ta1[i],Vs_Ta2[i]) == Vs_Ta1[i]:
      Action[i] = 1
    elif max(Vs_Ta0[i],Vs_Ta1[i],Vs_Ta2[i]) == Vs_Ta2[i]:
      Action[i] = 2

  #check the end of iteration
  count = 0
  for i in range(NumberOfState):
    if abs(Previous_Value[i]-Value[i])<0.001:
      count = count + 1

  if count == NumberOfState:
    flag_stop = True

  if not flag_stop:
    Vs = [[Value[col] for col in range(NumberOfState)] for row in range(NumberOfState)]

print("No.",NumberOfIteration," iteration:")
print("Action:")
print(Action)
print("Value:")
print(Value)
print("Previous Value:")
print(Previous_Value)
print("Does it finish? : ",flag_stop)

No. 71  iteration:
Action:
[1, 0, 0, 0]
Value:
[14.17746034 15.75364248 15.68971953 22.75889642]
Previous Value:
[14.17655157 15.75273371 15.68881077 22.75798765]
Does it finish? :  True
